from __future__ import annotations
from typing import Any

def decode_cid(data: str | bytes) -> dict[str, Any]: ...
def encode_cid(data: bytes) -> str: ...
def decode_car(data: bytes) -> tuple[dict[str, Any], dict[bytes, dict[str, Any]]]: ...
def decode_dag_cbor(data: bytes) -> dict[str, Any]: ...
def decode_dag_cbor_multi(data: bytes) -> list[dict[str, Any]]: ...
def encode_dag_cbor(data: dict[str, Any]) -> bytes: ...
def decode_multibase(data: str) -> tuple[str, bytes]: ...
def encode_multibase(code: str, data: str | bytes) -> str: ...
